name: "🔍 Enforce Changelog Requirements"

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

permissions:
  contents: read

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 🔍 Enforce Changelog Requirements
        uses: dangoslen/changelog-enforcer@v3
        with:
          changeLogPath: resources/RELEASE_NOTES.md
          skipLabels: |
            skip-changelog
            documentation
